/**
 * Deployed addresses, per chain.
 *
 * Generated by scripts/demo.mjs from the deployment it just broadcast. Every address in here was
 * created by a transaction rather than typed by hand.
 */
export type Deployment = {
  registry: `0x${string}`;
  oracle: `0x${string}`;
  volSurface: `0x${string}`;
  paidOrders: `0x${string}`;
  underwriterVault: `0x${string}`;
  swapVenue: `0x${string}`;
  creditLine: `0x${string}`;
  termRepo: `0x${string}`;
  accrualStrip: `0x${string}`;
  deployedAtBlock: number;
};

export const DEPLOYMENTS: Partial<Record<number, Deployment>> = {
  4663: {
    registry: '0x59AF421cB35fc23aB6C8ee42743e6176040031f4' as `0x${string}`,
    oracle: '0x4fb87c52Bb6D194f78cd4896E3e574028fedBAB9' as `0x${string}`,
    volSurface: '0xEd8d61f42dC1E56aE992D333A4992C3796b22A74' as `0x${string}`,
    paidOrders: '0x47eb28D8139A188C5686EedE1E9D8EDE3Afdd543' as `0x${string}`,
    underwriterVault: '0x52d2878492EF30d625fc54EC52c4dB7f010d471e' as `0x${string}`,
    swapVenue: '0x7f1C87Bd3a22159b8a2E5D195B1a3283D10ea895' as `0x${string}`,
    creditLine: '0x560A0c0CA6B0A67895024dae77442C5fd3DC473e' as `0x${string}`,
    termRepo: '0x27e5Ee255a177D1902D7FF48D66f950ed9408867' as `0x${string}`,
    accrualStrip: '0xc7253857256391E518c4aF60aDa5Eb5972Dd6Dbc' as `0x${string}`,
    deployedAtBlock: 59727272,
  },
};

export function deploymentFor(chainId: number): Deployment {
  const found = DEPLOYMENTS[chainId];
  if (!found) {
    throw new Error(
      `Marian is not deployed on chain ${chainId}. Run scripts/demo.mjs, which writes this map.`,
    );
  }
  return found;
}

export const isDeployed = (chainId: number): boolean => DEPLOYMENTS[chainId] !== undefined;
