#!/usr/bin/env node
/**
 * Emit the ABIs the SDK needs from the Foundry build output.
 *
 * Hand-maintained ABIs drift from the contracts silently: a renamed argument or a changed return
 * tuple produces a client that decodes garbage rather than one that fails to compile. This reads
 * `contracts/out` instead, so the only way for the SDK to disagree with the chain is for someone to
 * skip running it, which `pnpm build` does not allow.
 *
 *   node scripts/emit-abis.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'contracts', 'out');

const CONTRACTS = [
  ['PaidOrders', 'PaidOrders.sol'],
  ['UnderwriterVault', 'UnderwriterVault.sol'],
  ['VolSurface', 'VolSurface.sol'],
  ['CreditLine', 'CreditLine.sol'],
  ['TermRepo', 'TermRepo.sol'],
  ['AccrualStrip', 'AccrualStrip.sol'],
  ['AssetRegistry', 'AssetRegistry.sol'],
  ['EquityOracle', 'EquityOracle.sol'],
  ['UniswapV3Venue', 'UniswapV3Venue.sol'],
];

const parts = [
  '// Generated by scripts/emit-abis.mjs from the Foundry build output. Do not hand-edit.',
  '// Regenerate with: pnpm forge:build && node scripts/emit-abis.mjs',
  '',
];

for (const [name, file] of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8'));
  parts.push(`export const ${name.toLowerCase()}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`);
  parts.push('');
}

const target = join(root, 'packages', 'sdk', 'src', 'abis.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, parts.join('\n'));
console.log(`wrote ${target} (${CONTRACTS.length} ABIs)`);
