#!/usr/bin/env node
/**
 * Verify every candidate ticker against Robinhood Chain and write `data/assets.json`.
 *
 * Nothing enters the app's asset list on trust. For each candidate this reads the symbol, decimals,
 * multiplier and halt flags from the token, and the pair, fee tier and observation ring from the
 * pool, and drops anything whose pool is not actually that equity against USDG or cannot serve the
 * TWAP window the oracle is configured for. A wrong pair is the one misconfiguration that produces
 * a plausible wrong price instead of an error.
 *
 *   node scripts/refresh-assets.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SEL, ethCallBatch, toBigInt, toAddress, decodeString } from './rpc.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const USDG = '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168';
const MIN_CARDINALITY = 200;

const candidates = JSON.parse(readFileSync(join(root, 'data', 'candidates.json'), 'utf8'));

const chunk = (items, size) =>
  Array.from({ length: Math.ceil(items.length / size) }, (_, i) => items.slice(i * size, i * size + size));

const verified = [];
const rejected = [];

for (const group of chunk(candidates, 6)) {
  const calls = [];
  for (const c of group) {
    calls.push(
      { to: c.address, data: SEL.symbol },
      { to: c.address, data: SEL.decimals },
      { to: c.address, data: SEL.uiMultiplier },
      { to: c.address, data: SEL.newUIMultiplier },
      { to: c.address, data: SEL.effectiveAt },
      { to: c.address, data: SEL.paused },
      { to: c.address, data: SEL.oraclePaused },
      { to: c.pool, data: SEL.token0 },
      { to: c.pool, data: SEL.token1 },
      { to: c.pool, data: SEL.fee },
      { to: c.pool, data: SEL.slot0 },
    );
  }
  const results = await ethCallBatch(calls);

  group.forEach((c, i) => {
    const r = results.slice(i * 11, i * 11 + 11);
    const [symbol, decimals, multiplier, nextMultiplier, effectiveAt, paused, oraclePaused, token0, token1, fee, slot0] = r;

    const reject = (why) => rejected.push({ symbol: c.symbol, address: c.address, why });

    if (!symbol || !multiplier) return reject('token did not answer');
    if (Number(toBigInt(decimals)) !== 18) return reject(`decimals ${toBigInt(decimals)}`);
    if (toBigInt(multiplier) === 0n) return reject('zero multiplier');

    const t0 = toAddress(token0);
    const t1 = toAddress(token1);
    if (!t0 || !t1) return reject('pool did not answer');
    const assetIsToken0 = t0.toLowerCase() === c.address.toLowerCase();
    const usdgSide = assetIsToken0 ? t1 : t0;
    const assetSide = assetIsToken0 ? t0 : t1;
    if (assetSide.toLowerCase() !== c.address.toLowerCase()) return reject('pool does not hold this equity');
    if (usdgSide.toLowerCase() !== USDG.toLowerCase()) return reject('pool is not against USDG');

    // slot0 returns seven words on a standard v3 pool; observationCardinality is the fourth.
    const words = slot0.slice(2).match(/.{64}/g) ?? [];
    if (words.length < 7) return reject(`slot0 returned ${words.length} words`);
    const cardinality = parseInt(words[3], 16);
    if (cardinality < MIN_CARDINALITY) return reject(`cardinality ${cardinality}`);

    verified.push({
      symbol: decodeString(symbol) ?? c.symbol,
      address: c.address,
      decimals: 18,
      pool: c.pool,
      fee: Number(toBigInt(fee)),
      assetIsToken0,
      observationCardinality: cardinality,
      uiMultiplier: toBigInt(multiplier).toString(),
      newUIMultiplier: toBigInt(nextMultiplier)?.toString() ?? null,
      effectiveAt: Number(toBigInt(effectiveAt) ?? 0n),
      paused: toBigInt(paused) === 1n,
      oraclePaused: toBigInt(oraclePaused) === 1n,
      /** True when this ticker has ever paid out on chain. The multiplier is the only evidence. */
      paysDistributions: toBigInt(multiplier) > 10n ** 18n,
    });
  });
}

verified.sort((a, b) => a.symbol.localeCompare(b.symbol));

const payload = {
  chainId: 4663,
  usdg: USDG,
  measuredAt: new Date().toISOString(),
  note: 'Generated by scripts/refresh-assets.mjs. Every field was read from Robinhood Chain.',
  assets: verified,
  rejected,
};

writeFileSync(join(root, 'data', 'assets.json'), JSON.stringify(payload, null, 2));
const payers = verified.filter((a) => a.paysDistributions);
console.log(`verified ${verified.length}, rejected ${rejected.length}`);
console.log(`distribution payers (multiplier above 1e18): ${payers.length} -> ${payers.map((a) => a.symbol).join(', ')}`);
for (const r of rejected) console.log(`  rejected ${r.symbol}: ${r.why}`);
